// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQsOXIOSopaJLd-cURxnwa4EsEbiAMQAY',
    appId: '1:607407978475:web:fa6e6bc325f64b36a98bae',
    messagingSenderId: '607407978475',
    projectId: 'dudh-passbook',
    authDomain: 'dudh-passbook.firebaseapp.com',
    storageBucket: 'dudh-passbook.firebasestorage.app',
    measurementId: 'G-GMCZLGM56K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMxAy2KvJQOa03dZe_cM72F95Kl-ldmeA',
    appId: '1:607407978475:android:af1e22fa6837e26aa98bae',
    messagingSenderId: '607407978475',
    projectId: 'dudh-passbook',
    storageBucket: 'dudh-passbook.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlrSYb0RHeqVN33pHZYYO0vIrjkeI-gaY',
    appId: '1:607407978475:ios:5ac9dc2e66ccf181a98bae',
    messagingSenderId: '607407978475',
    projectId: 'dudh-passbook',
    storageBucket: 'dudh-passbook.firebasestorage.app',
    androidClientId: '607407978475-al8heo2ih1vc40huk5u733c3u4s25fpj.apps.googleusercontent.com',
    iosClientId: '607407978475-smao64kf1060mp2hkqc9s09a5f6397rd.apps.googleusercontent.com',
    iosBundleId: 'com.dairymaster.pro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlrSYb0RHeqVN33pHZYYO0vIrjkeI-gaY',
    appId: '1:607407978475:ios:c386c35dbb5768e3a98bae',
    messagingSenderId: '607407978475',
    projectId: 'dudh-passbook',
    storageBucket: 'dudh-passbook.firebasestorage.app',
    androidClientId: '607407978475-al8heo2ih1vc40huk5u733c3u4s25fpj.apps.googleusercontent.com',
    iosClientId: '607407978475-88lpicqhv9n17g7gjq6bclnm3ghrnjn4.apps.googleusercontent.com',
    iosBundleId: 'com.dairymaster.pro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQsOXIOSopaJLd-cURxnwa4EsEbiAMQAY',
    appId: '1:607407978475:web:602702744f208987a98bae',
    messagingSenderId: '607407978475',
    projectId: 'dudh-passbook',
    authDomain: 'dudh-passbook.firebaseapp.com',
    storageBucket: 'dudh-passbook.firebasestorage.app',
    measurementId: 'G-1E6YYDTGDL',
  );

}